### PR TITLE
I have added my details : AvidCoder

### PR DESCRIPTION
**Pull request by AvidCoder101**
@iamdevvalecha I have added my details. Thanks

### CODE REVIEW

**Review by CodingSpecies — APPROVED** [review]
## Thank you for contributing! This PR is successfully part of Hacktoberfest! 🎊

**Review by CodingSpecies — CHANGES_REQUESTED** [review]
Please can you rename the file to your username? @AvidCoder101

**Comment by AvidCoder101** [comment]
I have changed my image @CodingSpecies. Please merge, thanks (:

**Review by CodingSpecies — APPROVED** [review]
## Thank you for contributing! This PR is successfully part of Hacktoberfest! 🎊

**Pull request merged**
