### PR TITLE
Hello ! I added MD file and user profile in jpg format 

### PR DESCRIPTION
**Pull request by sanamkandar**

### CODE REVIEW

**Comment by sanamkandar** [comment]
i added myself, review PR #270

**Review by CodingSpecies — APPROVED** [review]
## Thank you for contributing! This PR is successfully part of Hacktoberfest! 🎊

**Comment by sanamkandar** [comment]
> ## Thank you for merge but this repo is exclued with respect to hacktoberfest so, it will not be counted .

**Comment by CodingSpecies** [comment]
@sanamkandar yes, this is true, I realised this. #271 . See if this label  helps.

**Comment by sanamkandar** [comment]
> @CodingSpecies  so should i again created PR ?

**Comment by CodingSpecies** [comment]
No, this repo isn't part of hacktoberfest, https://github.com/Binary-Cumates/Hacktoberfest-21-Open-First-PR/issues/271 this issue explains. Sorry for the confusion. @sanamkandar

**Comment by sanamkandar** [comment]
It's okay no worries!

**Pull request merged**
