### PR TITLE
added devboy

### PR DESCRIPTION
**Pull request by DevBoy69**

### CODE REVIEW

**Review by CodingSpecies — CHANGES_REQUESTED** [review]
Please rename your image to your name please @DevBoy69

**Review by CodingSpecies — APPROVED** [review]
## Thank you for contributing! This PR is successfully part of Hacktoberfest! 🎊

**Comment by DevBoy69** [comment]
If this PR is part of hacktoberfest'21 then why it is showing as **Excluded Project**
image

**Comment by CodingSpecies** [comment]
@DevBoy69 I am not sure, this repo is part of hacktoberfest, 
@iamdevvalecha can you please help @DevBoy69?

**Pull request merged**
