### PR TITLE
ADDED a BASE Contributing.md file, Will edit more

### PR DESCRIPTION
**Pull request by prabaljainn**
please do consider this PR and i'll be updating more 

and add Hacktoberfest tag if possible

### CODE REVIEW

**Comment by CodingSpecies** [comment]
#208

**Review by CodingSpecies — CHANGES_REQUESTED** [review]
Please @prabaljainn can the `Contributing` in the file name be in uppercase letters, after that it should be good for hacktoberfest, and can be merged.

**Comment by prabaljainn** [comment]
Ok ma'am

**Comment by prabaljainn** [comment]
ma'am done Changing Name to UpperCASE

**Comment by prabaljainn** [comment]
Ma'am

**Comment by prabaljainn** [comment]
ma'am please add hacktoberfest tag

**Comment by prabaljainn** [comment]
ma'am pls add hacktoberfest tag

**Review by CodingSpecies — APPROVED** [review]

**Comment by CodingSpecies** [comment]
@prabaljainn thank you, hacktoberfest accepted.

**Pull request merged**
