### PR TITLE
First time

### PR DESCRIPTION
**Pull request by Paimon-food**
Created a text file and added an image. Thank you.

### CODE REVIEW

**Review by CodingSpecies — CHANGES_REQUESTED** [review]
Please can you rename your image file to just `Vinayak.jpg`? Thank you @Paimon-food

**Comment by Paimon-food** [comment]
Hi is it fine now ...Sorry it took me a lot of time to edit it im a beginner

**Comment by Paimon-food** [comment]
Ahh i got my mistake ...I will create a new request soory for the iinconvenience

**Comment by CodingSpecies** [comment]
Thank you, @Paimon-food

**Pull request closed without merging**
