### PR TITLE
feat: new data added

### PR DESCRIPTION
**Pull request by akshitarora921**

### CODE REVIEW

**Review by CodingSpecies — CHANGES_REQUESTED** [review]
@akshitarora921 
Add your profile picture to the folder:
Add a picture picture of your choice in **static/images/.**  Accepted files are *png* and *jpg*, should be **squared** and minimum size `544x544` pixels. Ex.

`static/images/<YOUR-USERNAME>.png`

**Comment by akshitarora921** [comment]
Done

**Comment by akshitarora921** [comment]
please add 'hacktoberfest-accepted' label.

**Review by CodingSpecies — APPROVED** [review]
## Thank you for contributing! This PR is successfully part of Hacktoberfest! 🎊

**Pull request merged**
